[build]
  functions = "functions"

[dev]
  publish = "public"

[[redirects]]
  from = "/*"
  to = "https://benevolent-faloodeh-31bf10.netlify.app/.netlify/functions/api/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"